/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE licenseBaseService PLEASE EDIT ../license.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { License } from '../../domain/evertools_login_db/license';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../License.service.ts
 */

/*
 * SCHEMA DB License
 *
	{
		Connection_Code: {
			type: 'String',
			required : true
		},
		Url: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
	}
 *
 */
@Injectable()
export class LicenseBaseService {

    contextUrl: string = environment.endpoint + '/license';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * LicenseService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: License): Observable<License> {
        return this.http
            .post<License>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * LicenseService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * LicenseService.findByConnection_Code
    *   @description CRUD ACTION findByConnection_Code
    *
    */
    findByConnection_Code(id: string): Observable<License[]> {
        return this.http
            .get<License[]>(this.contextUrl + '/findByConnection_Code/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * LicenseService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<License> {
        return this.http
            .get<License>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * LicenseService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<License[]> {
        return this.http
            .get<License[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * LicenseService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: License): Observable<License> {
        return this.http
            .post<License>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
